services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx2025
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./conf.d/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      # - /Django2025/static:/Django2025/static:ro
      - /it_network/network_tickets/static:/it_network/network_tickets/static:ro
      - /it_network/network_tickets/media:/it_network/network_tickets/media:ro
    restart: always
